"use client"; // Ensures that this file is treated as a client component

import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "./context/UserContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en" className={inter.className}>
        <body>{children}</body>
      </html>
    </UserProvider>
  );
}
